<?php

// --- Secure session configuration ---

// Store the session ID only in cookies (not in the URL).
// This helps prevent session hijacking attacks where someone could steal your session ID from a link.
ini_set('session.use_only_cookies',1);

// Enable strict mode for sessions.
// This prevents PHP from accepting any session ID that was not generated by the server,
// protecting against session fixation attacks.
ini_set('session.use_strict_mode',1);

// --- Set session cookie settings for better security and control ---
session_set_cookie_params([
    'lifetime' => 1800,
    'domain' => 'ocalhost',
    'path' => '/',
    'secure' => true,
    // Helps protect against JavaScript attacks (like XSS).
    // It means JavaScript cannot read or change the session cookie.
    'httponly' => true
]);

